# Google Cloud Run service configuration
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: noah-ai-assistant
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Allocate 2 CPUs and 4GB memory for better performance
        run.googleapis.com/cpu: "2"
        run.googleapis.com/memory: "4Gi"
        # Auto-scale based on CPU utilization
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/execution-environment: gen2
    spec:
      serviceAccountName: noah-ai-service-account
      containers:
      - image: gcr.io/noah-ai-assistant/noah-ai-assistant:latest
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "noah-ai-assistant"
        - name: CLOUD_SQL_CONNECTION_NAME
          value: "noah-ai-assistant:us-central1:noah-analytics-db"
        - name: DATABASE_NAME
          value: "noah_analytics"
        - name: DB_USER
          value: "analytics_user"
        - name: REDIS_HOST
          value: "10.0.0.3"  # Replace with your Memorystore IP
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        # Health check configuration
        livenessProbe:
          httpGet:
            path: /_health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
  traffic:
  - percent: 100
    latestRevision: true